### ISSUE TITLE
snort output break

### ISSUE THREAD

**Issue by kinomakino** [csirtgadgets/csirtg-indicator-py#114]
By performing any combination of itype or tags, the output of snort causes this failure. thanks for your review

The deployment is a newly installed ubuntu 16 and CIFv3 installed via easybutton.

cif  --no-feed --itype ipv4 --columns indicator -f snort > ipv4.snort

Traceback (most recent call last):
  File "/usr/local/bin/cif", line 11, in <module>
    load_entry_point('cifsdk==3.0.0a28', 'console_scripts', 'cif')()
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/client.py", line 253, in main
    print(FORMATS[options.get('format')](data=rv, cols=args.columns.split(',')))
  File "/usr/local/lib/python2.7/dist-packages/csirtg_indicator/format/zsnort.py", line 97, in __repr__
    text.append(_indicator_to_rule(i, sid))
  File "/usr/local/lib/python2.7/dist-packages/csirtg_indicator/format/zsnort.py", line 72, in _indicator_to_rule
    return _dict_to_rule(r, opts)
  File "/usr/local/lib/python2.7/dist-packages/csirtg_indicator/format/zsnort.py", line 24, in _dict_to_rule
    rule['dport'],
TypeError: sequence item 1: expected string, NoneType found

**Comment by wesyoung** [comment]
try this:

`$ pip install https://github.com/csirtgadgets/csirtg-indicator-py/archive/master.zip`

https://github.com/csirtgadgets/csirtg-indicator-py/pull/116

also; you really should't create feeds without tags (eg: by using `--no-feed`), it won't leverage the whitelisting that goes on in building a feed, and it's a really bad habit to get into.

best practice is to create a different feed for each type of tag (eg: phishing|malware|...), each with it's own tuned confidence level for your environment. o/w you could easily start detecting various known good things (google, netflix, etc).

see: https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/Where-do-I-start-Feeds

let me know if that works and we'll get the fix into the next release...
