### ISSUE TITLE
Add optional "risk" field to format

### ISSUE THREAD

**Issue by deadbits** [csirtgadgets/csirtg-indicator-py#127]
The addition of an optional "risk" field for this would be great, imho. There's confidence currently, but depending on the age of the indicator, what type it is, it's description, etc., the risk level changes with each factor. Idk if you prefer that the user does that on their end but just adding my thoughts.

If I see a honeypot IP or cyber crime URL that has a high confidence but hasn't been updated in 6 months, chances are the risk is pretty low (of serving the same threat, if any, or being active at all)

"risk" could allow users to update the level from 0-100 (I was thinking in increments of 25 for some reason) each time they add or update an indicator.

Older indicators could be updated to have lower or zero risk, or if it's last seen date is very recently they could update the risk level, etc etc.

**Comment by deadbits** [comment]
"risk" meaning the threat level that an arbitrary indicators has - not correlated to any user/org end variables (like whether it's targeted at them or if they already have protection for it, etc), I think that'd be damn near impossible and very subjective to whoever adds/edits the risk. I'm thinking in broader terms than more specifically, since the _real_ risk level varies widely user/org to org.

**Comment by deadbits** [comment]
BTW : this looks like an easy add - I can put in a PR for this pretty quickly if you do decide it's a good idea for the project.

**Comment by wesyoung** [comment]
we've tried this in various forms over the years- back in the 2000's it was "severity" but became very complicated (and legally hard) to prescribe "what this means to you in your org". if i tell you something is risky (or worse- not?) and you get compromised, am i liable? kind of like road rules where you shouldn't signal to other drivers they can enter an intersection first.

confidence wasn't much better- but it conveyed an opinion that most operators understood. with that came "probability of not good" (which is what you see in CIFv4), but even that is subjective to "the types of data you're training with". that said- at-least within it's scope it's "statistically" sound and reproducible; which is i think the best you can hope for.

that said- we have a "merge pull requests" policy- so if it's useful to you; go for it. i don't have a strong opinion if you find it useful for you. i'd look at https://github.com/csirtgadgets/silver-meme though if you're messing with CIFv4. it's 'indicator v2'.

the trick is in describing "what problem are you trying to solve- " and if the obvious solution is "i need a risk field to solve this" then i'm all for it.

hth

**Comment by deadbits** [comment]
The "probability" field in silver-meme looks more in line with what I was thinking so this is good 👍

Thanks for the detailed response too, very helpful

**Comment by wesyoung** [comment]
np- i should have linked:

https://github.com/csirtgadgets/verbose-robot/wiki/Where-do-I-start-Confidence
https://github.com/csirtgadgets/verbose-robot/wiki/Where-do-I-start-Probability
https://csirtgadgets.com/search?q=probability

**Comment by deadbits** [comment]
Perfect, thanks for sending this over!  
 
 
 
 -- 
Adam M. Swanda
