### ISSUE TITLE
Format needs refactoring

### ISSUE THREAD

**Issue by JustinAzoff** [csirtgadgets/csirtg-indicator-py#46]
The formatter code currently takes a full data list and returns a fully rendered string.

Instead, the api should be something like

    write_to(fileobject, data)

or POSSIBLY

    get_lines(data)

which would yield each line in the output file.  so you would use each as

    with open(my_output_file, 'w') as f:
        zbro.write_to(f, data)

or

    with open(my_output_file, 'w') as f:
        for line in zbro.get_lines(data):
            f.write(line)

Which could also be written as

    with open(my_output_file, 'w') as f:
        f.writelines(zbro.get_lines(data))

Some are almost already like this, like the csv writer. All it needs is the the 

    output = StringIO()

to be a param.  Additionally, sending to stdout just means sending sys.stdout as the file object.

I'm not sure if they even need to be classes, I think a lot of this would be simpler as just standalone functions.

Supporting the old api can be easily done too, since you could easily pass a stringio object into the function to buffer the output. It's just impossible to go the other way.

It looks like one or two of the output modes would need to buffer the whole thing, but that's ok.

**Comment by wesyoung** [comment]
@JustinAzoff something like:

https://github.com/csirtgadgets/csirtg-indicator-py/compare/fix/46?expand=1

?
